projects:
  Stamps API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-northeast-2
        apiId: 2znkxvtbprgybboj47ilfqgvmy
        maxDepth: 2
extensions:
  amplify:
    version: 3
